"""add image field in hanger

Revision ID: 0da6c7f1a6b1
Revises: b6489e106c73
Create Date: 2024-09-14 19:31:54.292609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da6c7f1a6b1'
down_revision: Union[str, None] = 'b6489e106c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hangers', sa.Column('hanger_image_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'hangers', 'document_master', ['hanger_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hangers', type_='foreignkey')
    op.drop_column('hangers', 'hanger_image_id')
    # ### end Alembic commands ###
