"""initial migration

Revision ID: 186d11b67e60
Revises: f7e4226c02c6
Create Date: 2024-08-29 23:08:24.310820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '186d11b67e60'
down_revision: Union[str, None] = 'f7e4226c02c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.CHAR(length=50),
               existing_nullable=False)
    op.alter_column('document_master', 'uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.CHAR(length=50),
               existing_nullable=False)
    op.alter_column('roles', 'uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.CHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.CHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=sa.CHAR(length=50),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('roles', 'uuid',
               existing_type=sa.CHAR(length=50),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('document_master', 'uuid',
               existing_type=sa.CHAR(length=50),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('collections', 'uuid',
               existing_type=sa.CHAR(length=50),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
