"""user role middle table

Revision ID: b3f6251fd1e7
Revises: 3f086cc3f0ba
Create Date: 2024-08-15 15:56:20.817658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3f6251fd1e7'
down_revision: Union[str, None] = '3f086cc3f0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_uuid', table_name='user_roles')
    op.drop_column('user_roles', 'is_delete')
    op.drop_column('user_roles', 'modified_at')
    op.drop_column('user_roles', 'is_active')
    op.drop_column('user_roles', 'uuid')
    op.drop_column('user_roles', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('user_roles', sa.Column('uuid', mysql.CHAR(length=36), nullable=False))
    op.add_column('user_roles', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user_roles', sa.Column('modified_at', mysql.DATETIME(), nullable=True))
    op.add_column('user_roles', sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_user_roles_uuid', 'user_roles', ['uuid'], unique=True)
    # ### end Alembic commands ###
